# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp18c06bj1lnqs9z2to.mysql.rds.aliyuncs.com:3306/f4blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: authstr
    password: Z5m5086148









