server:
  port: 8011

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://192.168.30.106:8000/eureka/

spring:
  profiles:
    active: dev
  application:
    name: login
  mvc:
    view:
      prefix: /templates
      suffix: .html
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates
    charset: UTF-8
    allow-request-override: false
    cache: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.f4blog.base.model
  mapper-locations: classpath*:com/f4blog/**/mapping/*.xml
  configuration:
    #控制台打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #关闭驼峰命名转换
    map-underscore-to-camel-case: false









